### PR TITLE
Feature: Virtual Arsenal Manager

### PR DESCRIPTION
**Pull request by linkion**
#260 #258 #261 #
for real this time

### CODE REVIEW

**Comment by linkion** [comment]
Sorry for the closing and reopening of the same pull request, it's my first time using git.

Please do give me suggestions on what to do in the future.

**Comment by R3voA3** [comment]
> Sorry for the closing and reopening of the same pull request, it's my first time using git.
> 
> Please do give me suggestions on what to do in the future.

Don't worry, all good!

If you want to still work on this you can conver it to a draft
image

**Comment by R3voA3** [comment]
I'll added your branch to VS Code to keep working on it. Feel free to contribute to it as well. We can merge it when we are happy =)

**Comment by linkion** [comment]
How do you get hashmaps to work? 
I've defined _selectHashMap in the beginning, and I'm trying to set 
[_itemClass, [data]] from within ENH_fnc_virtualArsenalManager_switchNodeState

But getting _selectHashMap from within ENH_fnc_virtualArsenalManager_switchNodeState is returning `any` and not the hashmap.

I'm hoping to use _selectHashMap to save the selection to the profile and other stuff.

**Comment by linkion** [comment]
nvm, I just realized I have to set _selectHashMap to be a variable in uiNamespace.

**Comment by R3voA3** [comment]
Probably because it's a private variable. uiNamespace should be fine.

**Comment by linkion** [comment]
Note: use this function to init ace Arsenal.

[ace_arsenal_fnc_attributeInit](https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_attributeInit.sqf)

**Comment by R3voA3** [comment]
Current state

image

**Comment by linkion** [comment]
I'm having an issue with testing, the GUI is half gone and this error keeps popping up.

**Comment by linkion** [comment]
Is there a cache for arma 3 mods? since I'm also having an issue where the mod isn't updating anymore when I build it.

**Comment by R3voA3** [comment]
Did you sync your local repository? Otherwise I will check tomorrow morning

**Comment by linkion** [comment]
yeah, I also unpacked the PBO that's built and it is updated

**Comment by linkion** [comment]
It has to be an older version in my screenshot since when I click on a folder all the debug 3DEN notifications started popping up, even though I deleted those ages ago.

**Comment by linkion** [comment]
Just checked the function viewer ingame and none of the functions are being updated, even though the unpacked pbo shows that they should be.

Arma has to have some kind kind of cache or something, the mod loaded doesn't match the mod in the mods folder

**Comment by linkion** [comment]
fixed it, cfgFunctions wasn't updated to the new folder path.

**Comment by linkion** [comment]
so I've fixed what I thought would have worked with ace by instead editing the 3den attribute "ace_arsenal_attribute"

And I added a TODO, to add a second checkbox for whether to use BI virt arsenal since most groups who run with ace don't include BI arsenals.

So it would be nice if the GUI would detect if `isClass(configFile >> "CfgPatches" >> "ace_arsenal")` is true and then show the ace and BI arsenal checkboxes, else default to BI arsenal

**Comment by linkion** [comment]
Also, can we extend the window width-wise and have the right half to show the select item descriptions and stats for weapons and ammo, like what we see in the ace arsenal?



And to have the bottom half of that panel be another table view for compatible attachments like scopes, pointers, and magazines.


bask in the glory of my terrible ms paint skills

**Comment by linkion** [comment]
*for compatible items, they'll be separated by attachment type, not mod (scopes, pointers, bipods, magazines, etc.)

**Comment by R3voA3** [comment]
> So it would be nice if the GUI would detect if isClass(configFile >> "CfgPatches" >> "ace_arsenal") is true and then show the ace and BI arsenal checkboxes, else default to BI arsenal

Good idea.

> Also, can we extend the window width-wise and have the right half to show the select item descriptions and stats for weapons and ammo, like what we see in the ace arsenal?
Stats are planned.

**Comment by linkion** [comment]
I almost finished up tvItemInit. 

Need to set up selection/deselection and figure out a way to update the main table view to reflect what is currently selected.

Updating based on VAM_selectHashMap is the route I will go; this will also open up shortly to load the selection hashmap from the profile.

Currently, the accessories table view is just floating since I don't need to learn to work with GUIs.

**Comment by R3voA3** [comment]
image

**Comment by linkion** [comment]
Currently exam season for me, and was pretty stretched thin

I've done some work in the attachments tree, now I'm gonna try to make it to be a full list when no weapon is selected, then split when there is one selected.

**Comment by linkion** [comment]
Getting a weird error with my new function
`Error GIAR pre stack size violation`

I added functionality to load a _selectHashMap from an 3den object and I added it to arsenalPrototype to run when the window opens.

loadObject uses _display since it has a dialog popup for when ace mod is loaded to choose between using the ace arsenal attribute or BI arsenal attribute

**Comment by R3voA3** [comment]
> Getting a weird error with my new function `Error GIAR pre stack size violation`
> 
> I added functionality to load a _selectHashMap from an 3den object and I added it to arsenalPrototype to run when the window opens.
> 
> loadObject uses _display since it has a dialog popup for when ace mod is loaded to choose between using the ace arsenal attribute or BI arsenal attribute

So far I know this error is caused by a large array that has a wrong syntax. For example a missing bracket.

**Comment by linkion** [comment]
I'm having some issues with handleItemStats

It's not working...

The bars aren't changing positions, even with the random test

**Comment by linkion** [comment]
nvm, it's because the ctrl isn't being inputted as a parameter

**Comment by linkion** [comment]
I'm getting some weird stuff

In the function I'm getting the correct display but the _ctrlProgress_1 is incorrect and unrecognizable

Initial creation

In handleItemStats

**Comment by linkion** [comment]
figured it out, it's because the IDC_PROGRESS_* were not defined in the function

works now

**Comment by linkion** [comment]
Now all that's left is:

- loading from selected object
- loading from profile
- exporting to SQF

**Comment by linkion** [comment]
working on loading from selected object and ran into that arma 3 stores BI ammoBox in the weirdest way



it's a string with which the array is within and calling toArray just spews out random numbers

**Comment by linkion** [comment]
fixed it by using `[_object] call BIS_fnc_getVirtualWeaponCargo`

**Comment by linkion** [comment]
I think the UI is finally ready to get its config setup

Though I'd like to add frames around each table view

We'll work on loading from the profile later

**Comment by linkion** [comment]
idk why but _ctrlProgress_1 just doesn't want to listen to the commands

**Comment by R3voA3** [comment]
Looking good. Unfortunately I dont have much time atm to work on this.

**Comment by linkion** [comment]
made ctrlAddEventHandler fire once on creation for AccTV since some weird glitch where clicking the same item in the main TV twice would break the AccTV

**Comment by linkion** [comment]
facepalm-really
I just realized why my AccTV and ProgressBar1 don't listen to me.

they're both idc = 40... 😭

**Comment by linkion** [comment]
Also debating whether or not to remove stats since I don't think it's needed and just clutters the UI while being hard to implement

**Comment by R3voA3** [comment]
> Also debating whether or not to remove stats since I don't think it's needed and just clutters the UI while being hard to implement

We could create a sub-ui showing the stats if needed.

**Comment by linkion** [comment]
Huh, also, I ran a profiler, and with large modsets, the initialization takes likes 2 seconds. 

Most egregious, the accessory TV init is taking 300 ms, which causes a lag between selecting weapons.

At least the switchNodeState is really fast.

**Comment by linkion** [comment]
Can the accTV asynchronously load somehow?

Everything about loading the accessories is slow, the retrieval of mags, the filling of the TV.
While it isn't really needed immediately.

All except for retrieving the other compatible items using `ENH_fnc_compatibleItems`.

**Comment by R3voA3** [comment]
> Can the accTV asynchronously load somehow?
> 
> Everything about loading the accessories is slow, the retrieval of mags, the filling of the TV. While it isn't really needed immediately.
> 
> All except for retrieving the other compatible items using `ENH_fnc_compatibleItems`.

Which function handles that?

**Comment by linkion** [comment]
> > Can the accTV asynchronously load somehow?
> > Everything about loading the accessories is slow, the retrieval of mags, the filling of the TV. While it isn't really needed immediately.
> > All except for retrieving the other compatible items using `ENH_fnc_compatibleItems`.
> 
> Which function handles that?

fn_VAM_tvItemInit

**Comment by linkion** [comment]
I'm gonna try to call the individual add TVitems using spawn, but I'm having some issues with actually killing them when _displayName or _class is nil

**Comment by linkion** [comment]
There's also quite the bug where with large modsets, the mainTV just freezes and is un-interactable, which is frustrating

And many things could be causing it, like the large amount of items, the pictures, maybe the eventHandler, or it could be something else loading and taking up the scheduler

though all the other controls, like close, work

**Comment by linkion** [comment]
The applyAttribute function is having some issues with the BI apply, ace works flawlessly

but BI only works if you were to apply and then open the attributes of the object.

I've tried setting the 3DENAttribute manually, but then I couldn't addAction for arsenal

**Pull request merged**
