### PR TITLE
fix variable name for itemshashmap and stuff

### PR DESCRIPTION
**Pull request by linkion**

### CODE REVIEW

**Comment by linkion** [comment]
There is a bug that I can't really fix where the 3DEN attributes interface doesn't show the actual just applied attribute for ACE.

**Comment by linkion** [comment]
image

**Review by R3voA3 — APPROVED** [review]

**Review by R3voA3 — APPROVED** [review]

**Comment by R3voA3** [comment]
Sorry. For some reason I thought this was still WIP.

I have fixed the merge issue and merged it.

**Comment by linkion** [comment]
thx

**Comment by linkion** [comment]
actually my fault, I didn't say that this was ready to merge, sry.

**Pull request merged**
